- sdk/src/connections/network/network.cpp
- sdk/src/connections/network/network.h
Changes were taken (with cherry-pick) from this PR:
https://github.com/analogdevicesinc/aditof_sdk/pull/761
> network.cpp/.h: changed m_mutex from simple mutex to recursive_mutex

- sdcard-images-utils/nxp/deboot.sh
> sdcard-images-utils: nxp: deboot.sh: Fix ToF repo link

- apps/server/server.h
- sdk/src/connections/network/network.cpp
> apps, sdk: fix max frame size sent/received over network

- README.md
Signed-off-by: rbudai98 <robert.budai@analog.com>
> README: updated links

- bindings/python/pybind11/attr.h
- bindings/python/pybind11/buffer_info.h
- bindings/python/pybind11/cast.h
- bindings/python/pybind11/chrono.h
- bindings/python/pybind11/complex.h
- bindings/python/pybind11/detail/class.h
- bindings/python/pybind11/detail/common.h
- bindings/python/pybind11/detail/descr.h
- bindings/python/pybind11/detail/init.h
- bindings/python/pybind11/detail/internals.h
- bindings/python/pybind11/detail/type_caster_base.h
- bindings/python/pybind11/detail/typeid.h
- bindings/python/pybind11/eigen.h
- bindings/python/pybind11/embed.h
- bindings/python/pybind11/eval.h
- bindings/python/pybind11/functional.h
- bindings/python/pybind11/gil.h
- bindings/python/pybind11/iostream.h
- bindings/python/pybind11/numpy.h
- bindings/python/pybind11/operators.h
- bindings/python/pybind11/options.h
- bindings/python/pybind11/pybind11.h
- bindings/python/pybind11/pytypes.h
- bindings/python/pybind11/stl.h
- bindings/python/pybind11/stl/filesystem.h
- bindings/python/pybind11/stl_bind.h
Signed-off-by: Timotei Molcut <timotei.molcut@analog.com>
> Update pybind11 version to 2.9.0

- examples/tof-viewer/src/ADIMainWindow.cpp
> examples/tof-viewer: add mkdir use case for linux log as well

- appveyor.yml
- bindings/opencv/dnn/readme.md
- bindings/opencv/imshow/readme.md
- bindings/opencv/maskrcnn/readme.md
- bindings/python/examples/dnn/readme.md
- bindings/python/examples/maskr_cnn/readme.md
- bindings/ros/README.md
- bindings/ros/aditof_roscpp/package.xml
- ci/appveyor/make_installer.bat
- ci/appveyor/make_zip.bat
- cmake/aditof-setup.iss.cmakein
- cmake/readme.md
- doc/itof/linux_build_instructions.md
- doc/itof/nxp_build_instructions.md
- doc/itof/windows_build_instructions.md
- examples/imshow-jetson/readme.md
- examples/imshow-xavier/readme.md
Signed-off-by: Timotei Molcut <timotei.molcut@analog.com>
> Changed apparitions of 'aditof-sdk-rework' to 'ToF'

- cmake/version.h.cmakein
Signed-off-by: Timotei Molcut <timotei.molcut@analog.com>
> Added licence to header files

- drivers/LICENSE
Adding the driver license file from the licensing team to the drivers folder.
> Adding LICENSE file for the device drivers.

- apps/uvc-app/buffer.proto
- apps/uvc-app/tof-sdk-interface.cpp
> apps/uvc: Implement setting and getting controls

- examples/data_collect/main.cpp
> examples/data-collect: Allow modes 7 and 10 only

- apps/server/server.cpp
Client might crash (so won't hang up) and next time will try to find
sensors (which are already opened for communication). So check if
client didn't hang up and cleanup sensors and start fresh.
> apps/server: Cleanup server if client didn't hang up

- CMakeLists.txt
> CMakeLists.txt: change project version to 3.0.0

- examples/data_collect/CMakeLists.txt
- examples/first-frame-network/CMakeLists.txt
- examples/first-frame/CMakeLists.txt
- examples/tof-viewer/CMakeLists.txt
- sdk/CMakeLists.txt
> sdk/CMakeLists.txt: add -fPic compiler flag if stubs are used

- sdk/src/cameras/itof-camera/camera_itof.cpp
> camera_itof.cpp: fix point cloud address

- sdk/src/cameras/itof-camera/camera_itof.cpp
> sdk/cameras/itof_camera: add condition to run adsd3500 withouth cfg

- sdk/src/cameras/itof-camera/camera_itof.cpp
> Set control for abAveraging on adsd3500

- sdk/src/cameras/itof-camera/camera_itof.cpp
> sdk: Remove redundant if (no functional changes)

- sdk/src/connections/target/adsd3500_sensor.h
> sdk/adsd3500_sensor.h: increase mp frame size

- sdk/src/cameras/itof-camera/camera_itof.cpp
- sdk/src/cameras/itof-camera/config/RawToDepthAdsd3500_mp.ini
> sdk: temp shift ab data with 7 bits to reduce brightness

- bindings/python/examples/first_frame/first_frame.py
- bindings/python/examples/first_frame/readme.md
The file first_frame.py is modified to display the received frame to the user. The corresponding readme file is also updated.
> Python examples - firstframe

- sdcard-images-utils/nxp/deboot.sh
- sdcard-images-utils/nxp/patches/ubuntu_overlay/step1/usr/lib/init_resize.sh
- sdcard-images-utils/nxp/runme.sh
Automatically resize the ROOTFS partition on first boot to fill the SD card.
> sdcard-images-utils/nxp: Add automatically resize mechanism

- examples/data_collect/main.cpp
> examples/data-collect: fix frame size for raw data saved to file

- bindings/python/examples/dnn/CMakeLists.txt
- bindings/python/examples/dnn/dnn.py
- bindings/python/examples/dnn/readme.md
Signed-off-by: Ravichandran <Srivatsan.Ravichandran@analog.com>
> Fixing issues in dnn example

- sdk/src/cameras/itof-camera/camera_itof.cpp
> sdk/src/camera_itof.cpp: validate crc for adsd3500 ccb

- examples/tof-viewer/tof-viewer_config_adsd3500.json
- sdk/src/cameras/itof-camera/camera_itof.cpp
- sdk/src/cameras/itof-camera/camera_itof.h
- sdk/src/cameras/itof-camera/config/config_walden_3500_nxp.json
- sdk/src/cameras/itof-camera/config/config_walden_nxp.json
- sdk/src/connections/target/adsd3500_sensor.cpp
> sdk: add option to set fps through json file

- examples/tof-viewer/include/ADIMainWindow.h
> examples/tof-viewer/ADIMainWindow.h: remove extra class name

- azure-pipelines.yml
- ci/azure/imx8-docker/Dockerfile
> ci: change imx docker

- README.md
> README.md: update build status links

- examples/first-frame-network/main.cpp
> examples/first-frame-network.cpp: change default frame type to qmp

- sdk/src/connections/target/adsd3500_sensor.cpp
- sdk/src/connections/target/adsd3500_sensor.h
> sdk/src/connections/adsd3500_sensor.cpp: reset device before opening

- CMakeLists.txt
> Change project version to 3.2.0

- cmake/version.h.cmakein
> cmake/version.h.cmakein: fix git branch and commit parse

- sdcard-images-utils/nxp/deboot.sh
- sdcard-images-utils/nxp/patches/ubuntu_overlay/step1/usr/share/systemd/tof-power-en.sh
SD card image changes: 
1. Add delay before 0P8_VDD enabling
2. Add "analog" user to i2c group
3. Install python pip on SD card image
> Sd card image tweaks

- examples/data_collect/main.cpp
> examples/data_collect: Use 'vga' for mode 5

- drivers/adsd3500/nvidia/L4T_34_1_1/src/tegra194-p2888-0001-p2822-0000.dts
Signed-off-by: rbudai <robert.budai@analog.com>
> nvidia driver: added device tree for AGX Xavier

- sdk/src/connections/target/adsd3500_sensor.cpp
> sdk/target/adsd3500: Handle gpio setup for both NXP and NVIDIA

- sdk/src/connections/target/adsd3100_sensor.cpp
> sdk/connections/adsd3100_sensor.cpp: change pixelformat to YUYV

- sdk/src/cameras/itof-camera/camera_itof.cpp
- sdk/src/connections/target/adsd3500_sensor.cpp
> sdk/src/adsd3500, camera_itof: set fps with adsd3500_write_cmd

- sdk/src/cameras/itof-camera/camera_itof.cpp
- sdk/src/cameras/itof-camera/camera_itof.h
- sdk/src/cameras/itof-camera/config/config_adsd3500_adsd3030_nvidia.json
- sdk/src/cameras/itof-camera/config/config_walden_3500_nxp.json
> sdk/camera_itof.cpp: set fsync through json

- sdk/src/cameras/itof-camera/camera_itof.cpp
- sdk/src/connections/target/adsd3100_sensor.cpp
- sdk/src/connections/target/adsd3500_sensor.cpp
> sdk: set modeInfo table version on target

- scripts/nxp/ros2_ws_setup.bash
Signed-off-by: rbudai <robert.budai@analog.com>
> ROS2: setup steps ON nxp

- ci/azure/lib.sh
- ci/azure/windows-build/install_deps.ps1
- doc/itof/linux_build_instructions.md
- doc/itof/nxp_build_instructions.md
- doc/itof/windows_build_instructions.md
- scripts/nxp/utils.sh
- scripts/windows/setup_project.bat
Signed-off-by: rbudai <robert.budai@analog.com>
> Glog scripts updated to master

- sdcard-images-utils/nxp/deboot.sh
> sdcard-images-utils: nxp :deboot.sh: Install some default python packages

- sdcard-images-utils/nxp/deboot.sh
> sdcard-images-utils: nxp: deboot.sh: Install SDK

- examples/data_collect/CMakeLists.txt
> examples: data_collect: CMakeLists.txt: Link with pthread

- bindings/python/aditofpython.cpp
- sdk/include/aditof/camera.h
- sdk/src/cameras/itof-camera/camera_itof.cpp
- sdk/src/cameras/itof-camera/camera_itof.h
> sdk: Add API to set/get extra adsd3500 parameters

- scripts/windows/setup_project.bat
--
Added possibility to use depth compute stubs when using setup_project.bat
Signed-off-by: Daniyal Yasin <daniyalyasin93@gmail.com>
> Improved setup_project.bat

- drivers/adsd3500/nvidia/L4T_34_1_1/src/adsd3500.c
Fix framerate control by saving the control value and applying before stream-on. This is required when ADSD3500 is reset and internal stored value is reset to default.
> drivers: adsd3500: nvidia: adsd3500.c: Fix FPS update

- azure-pipelines.yml
> azure-pipelines.yml: re-enable vs2022 build

- sdk/src/cameras/itof-camera/camera_itof.cpp
> sdk/src/camera_itof.cpp: fix memcpy in request frame for srmp

- sdk/src/cameras/itof-camera/camera_itof.cpp
> sdk/src/camera_itof: fix requestFrame

- ci/azure/lib.sh
- ci/azure/windows-build/install_deps.ps1
- doc/itof/linux_build_instructions.md
- doc/itof/nxp_build_instructions.md
- doc/itof/windows_build_instructions.md
- scripts/nxp/utils.sh
- scripts/windows/setup_project.bat
Old was: 0.3.5. The updated version is 0.6.0.
> Update all references to glog version

- README.md
> readme: Add wiki link to ADTF3175D

- examples/data_collect/main.cpp
- sdk/src/cameras/itof-camera/camera_itof.cpp
> sdk: add control to get imager type and fix data collect frame size

- doc/itof/linux_build_instructions.md
Updates to the Linux build instructions such that the user can include the depth compute libraries for the Linux host build.
doc/itof/linux_build_instructions.md
> Update linux build readme

- CMakeLists.txt
> cmake: Update project to v4.0.0

- sdk/src/connections/target/adsd3500_sensor.cpp
beta firmware look like this: 0.4.0.0
while release firmware look like this: 4.0.0.0
> sdk: Check minor if we detect beta fw version

- examples/data_collect/main.cpp
> examples/data-collect: fix subframes count for mp

- azure-pipelines.yml
> azure-pilelines.yml: remove ubuntu 18 build

- examples/tof-viewer/include/ADIView.h
- examples/tof-viewer/src/ADIMainWindow.cpp
- examples/tof-viewer/src/ADIView.cpp
Adding improved support for AB in the Viewer, while also addressing a related bug.
Features added:
- Log scale view of AB
- Auto-scaling of AB which can be overridden by added JSON parameters.
> Viewer ab fix

- doc/itof/linux_build_instructions.md
Update taking v4.1.1 release into account and some additional items that needed to be captured for a successful build.
> Update Linux host build instructions

- sdk/include/aditof/camera.h
- sdk/src/cameras/itof-camera/camera_itof.cpp
- sdk/src/cameras/itof-camera/camera_itof.h
An API to request the ADSD3500 firmware version and git hash has been added.
> Added a user API for getting the ADSD3500 firmware version.

- sdk/src/cameras/itof-camera/config/RawToDepthAdsd3030_lr-native.ini
- sdk/src/cameras/itof-camera/config/RawToDepthAdsd3030_lr-qnative.ini
- sdk/src/cameras/itof-camera/config/RawToDepthAdsd3030_sr-native.ini
- sdk/src/cameras/itof-camera/config/RawToDepthAdsd3030_sr-qnative.ini
- sdk/src/cameras/itof-camera/config/RawToDepthAdsd3500_16bitAB_lr-native.ini
- sdk/src/cameras/itof-camera/config/RawToDepthAdsd3500_16bitAB_sr-native.ini
- sdk/src/cameras/itof-camera/config/RawToDepthAdsd3500_lr-native.ini
- sdk/src/cameras/itof-camera/config/RawToDepthAdsd3500_lr-qnative.ini
- sdk/src/cameras/itof-camera/config/RawToDepthAdsd3500_mp.ini
- sdk/src/cameras/itof-camera/config/RawToDepthAdsd3500_qmp.ini
- sdk/src/cameras/itof-camera/config/RawToDepthAdsd3500_sr-native.ini
- sdk/src/cameras/itof-camera/config/RawToDepthAdsd3500_sr-qnative.ini
Updated AB threshold and Gaussian Filter size
> min ab thresh and filter size changed

- sdcard-images-utils/nxp/deboot.sh
- sdcard-images-utils/nxp/runme.sh
Modified runme.sh and deboot.sh to allow specific branch building on NXP and add SDK version to the NXP image name
> Modify runme sh

- ci/azure/windows-build/build_sdk.ps1
- ci/azure/windows-build/install_deps.ps1
* Updated ci `cinst` comand to `choco install`
> ci/azure: cinst was removed from chocolatey, changed to choco install

- bindings/python/aditofpython.cpp
- sdk/include/aditof/camera.h
- sdk/src/cameras/itof-camera/camera_itof.cpp
- sdk/src/cameras/itof-camera/camera_itof.h
- sdk/src/cameras/itof-camera/config/RawToDepthAdsd3030_lr-mixed.ini
- sdk/src/cameras/itof-camera/config/RawToDepthAdsd3030_lr-native.ini
- sdk/src/cameras/itof-camera/config/RawToDepthAdsd3030_lr-qnative.ini
- sdk/src/cameras/itof-camera/config/RawToDepthAdsd3030_sr-mixed.ini
- sdk/src/cameras/itof-camera/config/RawToDepthAdsd3030_sr-native.ini
- sdk/src/cameras/itof-camera/config/RawToDepthAdsd3030_sr-qnative.ini
- sdk/src/cameras/itof-camera/config/RawToDepthAdsd3030_vga.ini
- sdk/src/cameras/itof-camera/config/RawToDepthAdsd3500_lr-mixed.ini
- sdk/src/cameras/itof-camera/config/RawToDepthAdsd3500_lr-native.ini
- sdk/src/cameras/itof-camera/config/RawToDepthAdsd3500_lr-qnative.ini
- sdk/src/cameras/itof-camera/config/RawToDepthAdsd3500_mp.ini
- sdk/src/cameras/itof-camera/config/RawToDepthAdsd3500_qmp.ini
- sdk/src/cameras/itof-camera/config/RawToDepthAdsd3500_sr-mixed.ini
- sdk/src/cameras/itof-camera/config/RawToDepthAdsd3500_sr-native.ini
- sdk/src/cameras/itof-camera/config/RawToDepthAdsd3500_sr-qnative.ini
- sdk/src/cameras/itof-camera/config/RawToDepthAdsd_pcm-native.ini
- sdk/src/cameras/itof-camera/config/config_adsd3500_adsd3030_new_modes.json
- sdk/src/cameras/itof-camera/config/config_adsd3500_adsd3030_old_modes.json
- sdk/src/cameras/itof-camera/config/config_crosby_adsd3500_new_modes.json
- sdk/src/cameras/itof-camera/config/config_crosby_nxp.json
- sdk/src/cameras/itof-camera/config/config_crosby_old_modes.json
- FPS moved from JSON to INI files in code and JSON and INI files
- VAUX_POWER_VOLTAGE and VAUX_POWER_ENABLE removed from code and JSON files
> Some clean up of the INI and JSON files

- bindings/python/examples/first_frame/first_frame.py
- sdk/src/cameras/itof-camera/camera_itof.cpp
- sdk/src/cameras/itof-camera/camera_itof.h
- sdk/src/cameras/itof-camera/config/config_adsd3500_adsd3030.json
- sdk/src/cameras/itof-camera/config/config_adsd3500_adsd3100.json
* Updates for changes to the JSON file.
* Fix for first_frame.py to stop the camera.
* Updates for new ini parameters.
> Adding new ini parameters

- tools/tof_lib_gen/generate_dpkg.bash
- tools/tof_lib_gen/ubuntu_20_04/adsd3030/Dockerfile
- tools/tof_lib_gen/ubuntu_20_04/crosby/Dockerfile
- tools/tof_lib_gen/ubuntu_22_04/adsd3030/Dockerfile
- tools/tof_lib_gen/ubuntu_22_04/crosby/Dockerfile
PR:
* docker builds forced build from skratch
* code styling
> Update tof gen

- examples/data_collect/main.cpp
* added ft to help menu
* enabled ir data format save and added format check
> examples/data_collect: allow saving raw, depth and ir format

- bindings/python/examples/dnn/dnn.py
- bindings/python/examples/dnn/readme.md
As well as updates to the readme.md file.
Additional changes to bring the style with other python examples.
Added quit via 'q'.
Added stop camera.
Added additional command line parameter.
> Explicit support for networking

- .gitignore
- examples/tof-viewer/src/ADIMainWindow.cpp
changes per this Jira ticket:
https://jira.analog.com/browse/TOFCMOS-421
> Viewer change

- sdk/src/cameras/itof-camera/camera_itof.cpp
Depth compute that lives on NXP should not produce XYZ frames as we are not sending them over network.
> sdk: Disable the generation of XYZ on NXP

- dependencies/adi/command_parser/command_parser.cpp
Also reverted the last attempt to fix it
> Added condition for mandatory argument in last position

- sdk/src/cameras/itof-camera/camera_itof.cpp
> itof-camera: check operator corrected

- sdk/CMakeLists.txt
copy tofi_compute and tofi_config to /usr/local/lib in case of using not opensource
> sdk/CMakeLists: copy tofi_compute and tofi_config to /usr/local/lib 

- dependencies/adi/command_parser/command_parser.cpp
Temporary solution for split argument.
> Added split parameter check

- sdcard-images-utils/nxp/patches/linux-imx/0060-drivers-media-spi-adsd3500-spi.c-Send-SPI-write-comm.patch
- sdcard-images-utils/nxp/patches/linux-imx/0061-drivers-media-i2c-adsd3500.c-Added-MP-mode-RAW12-res.patch
- sdcard-images-utils/nxp/patches/ubuntu_overlay/step1/usr/share/systemd/tof-power-en.sh
Pull request with individual commits for the SPI write command and added RAW12 resolutions for ADSD3500 SPI & I2C driver.
> ADSD3500 driver patches for RAW12 resolutions and SPI write command implementation.

- sdk/src/cameras/itof-frame/frame_impl.cpp
This reverts commit 72c12f778d23f8d7f1df5859ee97aa3c905d73fb.
> Revert "sdk/frame_impl.cpp: keep ir for now for backwards compat."

- examples/data_collect/main.cpp
- sdk/src/cameras/itof-camera/camera_itof.cpp
- sdk/src/cameras/itof-camera/camera_itof.h
- sdk/src/cameras/itof-frame/frame_handler_impl.cpp
- sdk/src/frame_handler_impl.h
This wasn't enough as FrameHandler class was also ignoring the directory that user could set.
Also refactor FrameHandler a bit.
> examples/data-collect: Fix --f parameter being ignored

- bindings/python/examples/first_frame/first_frame.py
- bindings/python/examples/streaming/depth-image-animation-pygame.py
Updated command line interface to support passing modes and better help.
> Update streaming sample with jet colormap

- drivers/adsd3500/nvidia/L4T_32_7_1/src/adsd3500_mode_tbls.h
- drivers/adsd3500/nvidia/L4T_32_7_1/src/tegra194-camera-adsd3500-a00.dtsi
- drivers/adsd3500/nvidia/L4T_34_1_1/src/adsd3500_mode_tbls.h
- drivers/adsd3500/nvidia/L4T_34_1_1/src/tegra194-p2888-0001-p2822-0000.dts
- drivers/adsd3500/nvidia/L4T_34_1_1/src/tegra194-p3668-all-p3509-0000.dts
> drivers/adsd3500/nvidia: Added RAW8 resloution to the DTS file.

- tools/misc/README.md
- tools/misc/rawparser.py
Add visualize_confidence() - works for qMP modes(raw file for MP modes doesnt have confidence data)
> Update rawparser to support conf

- sdk/include/aditof/camera.h
SetFrameType() and getAvailableFrameType() should be used instead.
> sdk/include: Mark setMode() and getAvailableModes() as deprecated

- bindings/python/aditofpython.cpp
- examples/tof-viewer/src/ADIView.cpp
- sdk/include/aditof/frame.h
- sdk/src/cameras/itof-camera/camera_itof.cpp
- sdk/src/cameras/itof-frame/frame_impl.cpp
- sdk/src/frame.cpp
- sdk/src/frame_impl.h
https://jira.analog.com/browse/TOFCMOS-667
> TOFCMOS-667

- sdk/CMakeLists.txt
- sdk/src/connections/target/buffer_processor.cpp
PR:
* Adding optimization flag for compilation (-Ofast for all platforms and -march=armv8-a+simd for NXP)
* Copy frame buffer before passing on to toficompute to have faster access from user space
> TOFCMOS 589

- bindings/python/examples/first_frame/first_frame.py
Bug fix in tag/5.0.0-rc1, firs_frame was not setting the chosen frame type
> TOFCMOS-705

- examples/tof-viewer/src/ADIMainWindow.cpp
Tof-Viewer: the temperature and frame counter in some cases showed unrelated values
> TOFCMOS-710

- sdk/src/cameras/itof-camera/camera_itof.cpp
To delete on merging dev:5.1.0 into main, refactored in dev branch
Going to be replaced by: https://github.com/analogdevicesinc/ToF/tree/iniparam_bugfix
> Quick-fix for setIniParam bug

- doc/itof/linux_build_instructions.md
- doc/itof/nxp_build_instructions.md
- scripts/nxp/setup.sh
- sdcard-images-utils/nxp/deboot.sh
Updated Build instructions for Linux and NXP in documents. Modified setup.sh to build NXP in release mode.
> Release mode build

- doc/itof/linux_build_instructions.md
- doc/itof/nxp_build_instructions.md
- scripts/nxp/setup.sh
- sdcard-images-utils/nxp/deboot.sh
Linux and NXP build instructions updated, NXP build script update
> Updated build instructions DOC for Linux, NXP and build instructions DOC

- scripts/nxp/setup.sh
> Bug fix to setup.sh

- bindings/python/examples/first_frame/first_frame.py
- bindings/python/examples/saveCCBToFile/saveCCBToFile.py
Updated saveCCB to save file with serial number and visualize first frame.
> Bugfix pybindings

- bindings/python/examples/first_frame/first_frame.py
- examples/first-frame/main.cpp
Removed mandatory config file from:
* examples/first-frame
* bindings/python/first-frame
> Removed config from first-frame examples

- examples/tof-viewer/include/ADIMainWindow.h
- examples/tof-viewer/src/ADIMainWindow.cpp
This fixes TOFCMOS-775. The issue was that the hovering feature was not offset for the value to true value for a given pixel.
> Viewer hover fix

- bindings/python/examples/dual_cameras/dual_cameras.py
- bindings/python/examples/saveCCBToFile/saveCCBToFile.py
- scripts/windows/setup_project.bat
1. Simplified windows build script
2. Improvements added to python bindings
3. Libaditof submodule commit update to match with the main branch of ToF
> Windows build script

- drivers/adsd3500/nxp/src/i2c/adsd3500.c
- drivers/adsd3500/nxp/src/spi/adsd3500-spi.c
- sdcard-images-utils/nxp/patches/linux-imx/0066-drivers-media-i2c-adsd3500.c-Added-new-RAW8-and-RAW1.patch
- sdcard-images-utils/nxp/patches/linux-imx/0067-drivers-media-spi-adsd3500-spi.c-Added-new-RAW8-and-.patch
Added new v4l2 resolutions for frame captures on nxp for both i2c and spi drivers
> drivers: adsd3500: nxp: src: Added RAW8 and RAW12 resolutions in i2c and spi source files

- scripts/windows/setup_project.bat
Build script was updated to add Visual Studio 2022. Libaditof branch switched to main.
> Update build script

- apps/server/server.cpp
> modified server for dual pulsatrix frame to not allocate confidence

- examples/tof-viewer/src/ADIView.cpp
Updated the viewer to support offline playback of recordings.
> Support offline playback.

- .github/workflows/codeql.yml
Adding codeql file to main branch
> Codeql advanced mode enable

- azure-pipelines.yml
Disabled 20.02 Ubantu and updated to Ubantu 22.04 as base
> Ubantu 20 02 disable

- sdcard-images-utils/nxp/patches/ubuntu_overlay/step1/usr/share/systemd/usb-gadget.sh
> usb-gadget.sh: removed unwanted lines

- apps/server/server.cpp
preventing to send the stream-off if stream-off already been sent.
This is reducing closing time for tof-viewer .
> preventing to send the stream-off.

- Web-UI/create-workspace.sh
- Web-UI/how_to_create_workspace.md
- sdcard-images-utils/nxp/deboot.sh
In deboot.sh 
- renamed workspace version to 6.1.0.
- gave user access to Tools folder.
> Readme workspace gz

- Web-UI/requirements/usb-gadget.sh
- Web-UI/web-1.0.0/network-mode-switch.sh
- sdcard-images-utils/nxp/patches/ubuntu_overlay/step1/usr/share/systemd/switch_mode_for_Win.sh
- sdcard-images-utils/nxp/patches/ubuntu_overlay/step1/usr/share/systemd/usb-gadget.sh
script to switch to RNDIS for windows.
> updated usb-gadget script to change between ECM/RNDIS also added shell

- tests/README.md
- tests/extract_results.ps1
- tests/sdk/sdk_stream_test/main.cpp
- tests/sdk/sdk_stream_test/readme.md
* Better return value categorization
* Stopping sensor added on return from failures, when necessary
* '-f'/'--f' optional, in which case it does not save files
* Test run in showing in the output
> Stopping of sensor

- tests/sdk/sdk_stream_test/main.cpp
* It will print all the tests result in table format.
> SDK_Stream_Test: Added test summary table prints

- apps/server/server.cpp
it is happening because of camDepthSensor object is getting reset before sending stream-off
> resolve the server seg fault issue
