analogdevicesinc/ToF

- sdcard-images-utils/nxp/patches/uboot-imx/0009-board-solidrun-common-tcpc-Handle-DISCOVER_IDENTITY-.patch
Vendor Defined Message DISCOVER IDENTITY should be handeled in order to
configure the TCPC port on some hosts.
> sdcard-image-utils: u-boot: tcpc: Handle DISCOVER_IDENTITY VDM

- sdcard-images-utils/nxp/deboot.sh
Add "htpdate" for date update on networks with NTP port closed,
ssh and "bc" for computing the voltages read back by ADC
> sdcard-images-utils: deboot.sh: Install htpdate bc and ssh

- sdcard-images-utils/nxp/patches/ubuntu_overlay/step1/usr/share/systemd/tof-power-en.sh
A requirement form HW team for setting the VAUX rail to 22V.This setting
is expected to be suitable for all imager modules.
> sdcard-images-utils: ubuntu_overlay: tof-power-en.sh: Set VAUX to 22V

- sdk/src/connections/usb/linux/usb_depth_sensor_linux.cpp
Free buffers before setting the new frametype and requesting new buffers
Signed-off-by: rbudai98 <robert.budai@analog.com>
> USB_DEPTH_SENSOR_LINUX: added VIDIOC_REQBUF 

- sdk/src/cameras/itof-camera/camera_itof.cpp
- sdk/src/cameras/itof-camera/camera_itof.h
These options read from INI file will be used to configure the ADSD3500.
> sdk: Make camera read from INI file the nb of bits for AB, Depth, Conf

- sdcard-images-utils/nxp/deboot.sh
- sdcard-images-utils/nxp/runme.sh
This PR create a sw-versions file in FAT partition for easyer identification of flashed SD card image
and also disable restricted and multiverse repos and generate a file with licences of all installed rootfs apps.
> sdcard-images-utils: Add versions file and generate licences.txt list

- apps/server/server.cpp
Client might crash (so won't hang up) and next time will try to find
sensors (which are already opened for communication). So check if
client didn't hang up and cleanup sensors and start fresh.
> apps/server: Cleanup server if client didn't hang up

- examples/tof-viewer/src/ADIMainWindow.cpp
- examples/tof-viewer/src/ADIView.cpp
The framerate of the point cloud and depth combination was limited to half that of the AB and depth combination - when using a decent GPU such as NVIDIA as opposed to an integrated GPU. This limitation was due to how the code treated point cloud and depth vs AB and depth. Point cloud and depth is now treated in the same manner as AB and depth. Point cloud and depth is now at the same rate as AB and depth. However, point cloud rendering is impacted by GPU activity.
> Frame rate was being limited by how the depth and point cloud windows

- sdk/src/connections/target/adsd3500_sensor.cpp
This is not a complete solution. There can be multiple formats for
"qmp". Same applies for "mp". Formats vary based on the number of AB,
depth and confidence bits that are set via .ini file.
> sdk/target: Change format based on mode ("qmp" or "mp")

- examples/data_collect/main.cpp
This avoids build error on Linux(Ubuntu, etc.)
> examples/data-collect: Initialize 'subFrames' variable

- sdk/src/cameras/itof-camera/camera_itof.cpp
ADSD3500 firmware is responding as expected to mode 10
dealias parameters. So remove using of mode 5 parameters
on mode 10 data.
> sdk: src: camera_itof.cpp: Fix dealias for mode 10

- sdk/src/cameras/itof-camera/camera_itof.cpp
- sdk/src/cameras/itof-camera/camera_itof.h
> sdk/camera_itof: copy ab data to buffer for mp only if ab is enabled

- sdk/src/connections/network/network.cpp
- sdk/src/connections/network/network.h
This fixes the issue where SDK would crash if unable to connect to
server (maybe wrong IP or server not up yet).
> sdk/network: Close the detached thread before Network gets destroyed

- sdcard-images-utils/nxp/patches/uboot-imx/0001-Add-imx8mp-solidrun-configuration-files-to-u-boot.patch
- sdcard-images-utils/nxp/patches/uboot-imx/0003-Add-imx8mp-solidrun-board-to-uboot-configuration.patch
- sdcard-images-utils/nxp/patches/uboot-imx/0004-fix-name-of-dtb-file-for-i.MX8MP-HummingBoard-Pulse.patch
- sdcard-images-utils/nxp/patches/uboot-imx/0005-imx8mp-add-eqos-ethernet-port-and-disable-fec.patch
- sdcard-images-utils/nxp/patches/uboot-imx/0006-imx8mp-add-memory-size-detection.patch
- sdcard-images-utils/nxp/patches/uboot-imx/0007-LFU-143-tcpc-Add-i2c-read-write-return-check.patch
- sdcard-images-utils/nxp/patches/uboot-imx/0008-imx8mp_solidrun-Enable-USB-Type-C-controller.patch
- sdcard-images-utils/nxp/patches/uboot-imx/0009-board-solidrun-common-tcpc-Handle-DISCOVER_IDENTITY-.patch
- sdcard-images-utils/nxp/patches/uboot-imx/0010-arch-arm-dts-Add-ADI-devicetree.patch
- sdcard-images-utils/nxp/patches/uboot-imx/0011-configs-imx8mp_solidrun_defoncifg-Set-boot-delay-to-.patch
- sdcard-images-utils/nxp/patches/ubuntu_overlay/step3/etc/fstab
1. Disable video in u-boot (no ADV7535 available on NXP carrier)
2. Auto mount /boot
3. Set u-boot delay timer to 0
> SD card image generator fixes

- sdk/src/connections/network/network.cpp
- sdk/src/connections/network/network_sensor_enumerator.cpp
Network connection was still having issues. If the device was not connected the system became unresponsive and the Viewer would not connect even when the device was ready.
* Reduced the connection time from 10s to 3s. Although a better way to do this would be to modify the Viewer, that is coming next.
* Clean up if the network connection fails.
> Adsd3500 network connect issue

- doc/itof/linux_build_instructions.md
> doc/itof/linux_build_instructions: add missing openGL libraries

- sdk/src/cameras/itof-camera/camera_itof.cpp
Continue to display an error message but continue the flow. It's possible that a default FPS is being used.
> sdk: Don't fail camera initialization if could not set FPS

- sdcard-images-utils/nxp/deboot.sh
> ToF: sdcard-images-utils: nxp: deboot.sh: Add missing user groups

- bindings/python/aditofpython.cpp
- sdk/include/aditof/camera.h
- sdk/src/cameras/itof-camera/camera_itof.cpp
- sdk/src/cameras/itof-camera/camera_itof.h
- Tested with one camera, adsd3500 can work in slave configuration where the host is triggering fsync instead of the adsd3500
> initial commit

- examples/tof-viewer/include/ADIMainWindow.h
- examples/tof-viewer/src/ADIMainWindow.cpp
1st reason to remove this:
It's not clear why this is required. The function that changes the mode is a blocking type function. Once it finishes the execution, the camera should be in the new mode.
2nd reason to remove this:
The function to wait for camera calls getFrame but at the same time there is a thread that also calls getFrame. This messes things up (especially depth compute) as neither depth compute nor geFrame are thread safe.
> examples/tof-viewer: Don't wait for camera ready

- apps/uvc-app/lib/stream.c
- apps/uvc-app/uvc-app.cpp
Fix for SEGMENTATION FAULT when UVC stream is stopped. The events list was still processed but events pointers are null.
Also add mechanism for graceful closing and cleaning on SIGINT (CTRL + C).
> apps: uvc-app: Fix SEG_FAULT on stream stop

- bindings/python/aditofpython.cpp
This is described in detail in: #204
> Included relevant header for windows to fix ssize_t not found 

- doc/mainpage.dox
ToF is more relevant as is the name of the repo.
> doc\doxygen: Update license and use ToF instead of Aditof

- drivers/adsd3500/nvidia/L4T_34_1_1/src/adsd3500.c
Initialize default framerate value to start streaming in cases when SET_FRAMERATE control is not 
explicitly called before STREAM-ON
> drivers: adsd3500: nvidia: adsd3500.c: Initialize framerate default to 10

- sdk/src/sensor_enumerator_factory.cpp
Having an offline sensor (no camera attached to the embedded platform such as NXP) can be useful to test the network server for example.
> sdk: Allow using offline mode on target as well (not just on PC)

- drivers/adsd3500/nvidia/L4T_34_1_1/src/adsd3500.c
Because frmfmt table was skipping first 2 elements the 256x320 and 1280x320 resolutions were rejected
> drivers: adsd3500: nvidia: L4T_34_1_1: src: adsd3500.c: Fix QVGA resolution

- sdk/src/cameras/itof-camera/nvidia/target_definitions.h
- sdk/src/connections/target/adsd3500_sensor.cpp
On Nvidia, v4l2 device name might vary depending on the I2C address or bus number.
Signed-off-by: Dan <dan.nechita@analog.com>
> sdk: Don't match length when comparing v4l2 names

- bindings/python/CMakeLists.txt
The SD card build was broken due to the libs folder missing. This update resolves that issue.
> Fixed issue with SD card image build if libs folder is missing.

- sdk/src/cameras/itof-camera/camera_itof.cpp
The depth compute was crashing. Disabling the confidence makes DC work. ToDo: investigate the cause of crash.
> sdk: Temporary disable the generation of confidence content

- sdk/common/adi/depth-compute-opensource/src/tofiCompute.cpp
In some usecases confidence or AB might not be needed.
> sdk/dc-opensource: Deinterleave AB or confidence only if pointer valid

- sdk/src/cameras/itof-camera/camera_itof.cpp
> sdk: Remove unnecessary memcpy of AB frame for Crosby native modes

- drivers/adsd3500/nvidia/L4T_32_7_1/src/tegra194-camera-adsd3500-a00.dtsi
- drivers/adsd3500/nvidia/L4T_34_1_1/src/tegra194-p2888-0001-p2822-0000.dts
- drivers/adsd3500/nvidia/L4T_34_1_1/src/tegra194-p3668-all-p3509-0000.dts
This patch will also fix the reset ADSD3500 problem but only for 1.25Gbps lanerate. For 2.5Gbps deskew is required form TX side
> drivers: adsd3500: nvidia: Configure for 1.25Gbps lane rate

- examples/tof-viewer/src/ADIToFRecorder.cpp
The frame has an internal structure (that refers to what content exists: depth, AB, etc. and the resolution for each of them). The current implementation of the recording process doesn't save anything about the frame structure. So when playback starts, we don't know how to construct the frame.
The quick fix is to assume depth and AB has been recorded. A full refactor is needed.
> examples/tof-viewer: Quick (dirty) fix to make playback work with 'raw'

- examples/data_collect/main.cpp
- examples/first-frame/main.cpp
The temperature read impacts the frame rate heavily. Move it to first-frame since it is useful to show an example of how to read laser and sensor temperatures.
> examples: Mode the temperature read from data-collect to first-frame

- apps/server/server.cpp
- apps/uvc-app/tof-sdk-interface.cpp
- sdk/include/aditof/depth_sensor_interface.h
- sdk/src/cameras/itof-camera/camera_itof.cpp
- sdk/src/connections/network/network_depth_sensor.cpp
- sdk/src/connections/network/network_depth_sensor.h
- sdk/src/connections/offline/offline_depth_sensor.cpp
- sdk/src/connections/offline/offline_depth_sensor.h
- sdk/src/connections/target/adsd3100_sensor.cpp
- sdk/src/connections/target/adsd3100_sensor.h
- sdk/src/connections/target/adsd3500_sensor.cpp
- sdk/src/connections/target/adsd3500_sensor.h
- sdk/src/connections/usb/linux/usb_depth_sensor_linux.cpp
- sdk/src/connections/usb/usb_depth_sensor.h
- sdk/src/connections/usb/windows/usb_depth_sensor_windows.cpp
This delay is now used for reading temperature but should not force other calls to adsd3500_read_cmd() that not need this delay. Also, validate the FPS value when calculating the time to wait in order to avoid division by 0.
> Allow setting the time to wait for adsd3500_read_cmd

- sdk/src/connections/target/gpio.cpp
This usually works when compiling with a native compiler but gives a compiler error when cross compiling. So use the exact header where close() is declared.
> sdk: Add missing header for close()

- bindings/python/CMakeLists.txt
- examples/data_collect/CMakeLists.txt
- examples/first-frame-network/CMakeLists.txt
- examples/first-frame/CMakeLists.txt
- examples/tof-viewer/CMakeLists.txt
- sdk/CMakeLists.txt
glog DLL is required to be next to each executable. These changes will copy the DLL during the build process.
> cmake: Copy the glog DLL when building on Windows

- apps/server/server.cpp
- examples/first-frame-network/main.cpp
- sdk/src/connections/network/network.cpp
- sdk/src/connections/network/network.h
Frame serialization in case of quarter MP requires 2 miliseconds and in case of MP requires 8 miliseconds in plus
app/server: added 1 byte in front of every libwebsocket packet to determine if the message is serialized or not
network_sensor: after libwebsocket obtains the message the first byte is checked and based in it's value the following part is deserialized or not
Frame transmission without serialization finalized. (Needs testing on MP datasizes)
> server and network_sensor: frame transmission without serialization

- sdcard-images-utils/nxp/patches/linux-imx/0051-drivers-media-i2c-adsd3500-add-Debugfs-read-support.patch
- sdcard-images-utils/nxp/patches/ubuntu_overlay/step1/usr/share/systemd/tof-power-en.sh
This commit implement ADSA3500 fault register read mechanism. There are 2 interfaces exposed:
- sysfs readback
- registering to a system event triggered by ADSD3500 interrupt
> sdcard-images-utils: nxp: patches: Add ADSD3500 interrupt handling

- sdcard-images-utils/nxp/runme.sh
The platform where NXP stored I.MX relevant repositories (Codeaurora) is discontinued. Now all the repos are moved on GitHub so update the build scripts accordingly.
> sdcard-images-utils: nxp: runme.sh: Switch to Github instead of codeaurora

- sdk/include/aditof/frame_operations.h
Without this the compilation will fail if any client code will try to call these functions.
> sdk: Export functions in frame_operations.h

- sdk/src/cameras/itof-camera/camera_itof.cpp
- sdk/src/cameras/itof-camera/mode_info.cpp
PR:
-when initializing the camera check if data for mode 5 is accurate, in case it is, the new mixed table is allocated
> Add mixed mode check

- sdk/src/cameras/itof-camera/camera_itof.cpp
The issue was that JBL filter was always ON no matter how it was set in the .ini file.
The fix is to set all JBL properties first and then enable/disable JBL filter. It seems that setting the JBL filter size would also enable it.
> sdk: Fix order in which JBL settings are being sent to adsd3500

- sdk/src/cameras/itof-camera/camera_itof.cpp
Issue:
The API `requestFrame` is reporting success status `Status::OK` even if internal API call `status = m_depthSensor->getFrame(frameDataLocation)` is failed.
Fix:
Return proper error code to application layer instead of `tatus::OK`.
> getFrame error should be reported to callee

- dependencies/adi/command_parser/command_parser.cpp
I found that when using multiple mandatory arguments, command parser will not store the [arguments, value] properly. This happened because of missing lines of code for handling these two case (for mandatory arguments):
- argument=value
- argument value
> Fixed parser problem with multiple mandatory arguments

- examples/tof-viewer/src/ADIToFRecorder.cpp
I observed this while playing back a recorded stream. The memory usage (seen in Visual Studio IDE) was constantly going up, reaching 4 GB in less than a minute.
After this fix, the memory usage remains around 800 MB but this value is not that important. What is important is the fact that memory usage no longer increases.
> examples/viewer: Cleanup frame details before creating a new frame

- sdk/src/cameras/itof-camera/camera_itof.cpp
- sdk/src/cameras/itof-camera/camera_itof.h
So far two additional free was added:
* freeing up the memory allocated for depthIniDataMap
* freeing up the json
So far there are other memory allocations in libtofi_compute that are not freed. The following stack trace shows the use of mallocs/callocs that are used without free, (while hitting the play button of ADIViwer two times):
```
=689017== HEAP SUMMARY:
==689017==     in use at exit: 13,371,176 bytes in 3,485 blocks
==689017==   total heap usage: 101,980 allocs, 98,495 frees, 183,719,747 bytes allocated
==689017== 
==689017== 586 (120 direct, 466 indirect) bytes in 1 blocks are definitely lost in loss record 2,229 of 2,271
==689017==    at 0x484DA83: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==689017==    by 0x56FBBEC: InitTofiConfig_isp (in …
```
> Viewer memory bug

- sdk/common/adi/depth-compute-opensource/src/tofiCompute.cpp
Depth compute considers that if a null pointer is provided for XYZ, it will just not produce point cloud. Therefore, we do the same for the open source implementation of depth compute.
> depth-compute-opensource: Avoid crash when providing a null XYZ pointer

- sdcard-images-utils/nxp/patches/linux-imx/0057-drivers-media-i2c-adsd3500.c-Modified-image-pixel-fo.patch
Added RAW8 resolutions for ADSD3100 and ADSD3030 sensors.
> sdcard-images-utils/nxp/patches/linux-imx: Changed image pixel format to

- sdk/src/connections/target/adsd3500_sensor.cpp
On target can cause unexpeted behaviour
> adsd3500_sensor.cpp: Initialize m_hostConnectionType variable. 

- sdk/src/cameras/itof-camera/camera_itof.cpp
Confidence data is comming from target as float (each pixel is a float).
> sdk: Fix setting confidence to half size

- doc/itof/nxp_build_instructions.md
- scripts/windows/setup_project.bat
Two fixes:
* NXP Build instructions now reference v5.0.0 tag.
* setup_project.bat changed to reference the repo we use for libwebsockets.
> Random fixes

- sdcard-images-utils/nxp/deboot.sh
Adding iperf3 to the list of modules to be installed on the NXP linux File system.
> Addid iperf3 to the list of modules to be installed on NXP file system

- scripts/nxp/setup.sh
Network is enabled by default so no need to pass that again to cmake. On NXP, by default, we want to use the closed source depth compute.
> scripts/nxp: Update cmake options

- sdk/src/cameras/itof-camera/config/RawToDepthAdsd3030_lr-mixed.ini
- sdk/src/cameras/itof-camera/config/RawToDepthAdsd3030_lr-native.ini
- sdk/src/cameras/itof-camera/config/RawToDepthAdsd3030_lr-qnative.ini
- sdk/src/cameras/itof-camera/config/RawToDepthAdsd3030_sr-mixed.ini
- sdk/src/cameras/itof-camera/config/RawToDepthAdsd3030_sr-native.ini
- sdk/src/cameras/itof-camera/config/RawToDepthAdsd3030_sr-qnative.ini
- sdk/src/cameras/itof-camera/config/RawToDepthAdsd3500_lr-mixed.ini
- sdk/src/cameras/itof-camera/config/RawToDepthAdsd3500_lr-native.ini
- sdk/src/cameras/itof-camera/config/RawToDepthAdsd3500_lr-qnative.ini
- sdk/src/cameras/itof-camera/config/RawToDepthAdsd3500_sr-mixed.ini
- sdk/src/cameras/itof-camera/config/RawToDepthAdsd3500_sr-native.ini
- sdk/src/cameras/itof-camera/config/RawToDepthAdsd3500_sr-qnative.ini
- sdk/src/cameras/itof-camera/config/RawToDepthAdsd_pcm-native.ini
DeltaCompEnabled and absumThresh are removed from the INI parameters list since they are not used.
> Removing deltaCompEnable and absumThresh from INI parameters since they are not used

- sdk/src/connections/network/network.cpp
The entire streaming on network is more stable on NVidia as host if we call the libwebsockets service routing twice when sending a command to server.
More specifically, this fixes the issue where, from time to time, the video streaming stops due to a 10s timeout then starts again.
> lws_callback_on_writeable() call must be called twice

- examples/tof-viewer/include/ADIMainWindow.h
- examples/tof-viewer/src/ADIMainWindow.cpp
Interrupts were continuously registered when connecting to a camera.
> ToF-Viewer: handler update

- examples/tof-viewer/src/ADIMainWindow.cpp
This prevents crash when ImGui::End() is called for a popup that couldn't be created. At this point in time I don't know the reasons for why popup can't be created.
> examples/viewer: Check whether modal popup was created or not

- scripts/nxp/setup.sh
This is to make it easier for the process of creating the SD card image.
> scripts/nxp: By default build with opensouce depth compute

- sdk/CMakeLists.txt
Due to deprecated CMAKE_COMPILER_IS_GNUCC change to CMAKE_CXX_COMPILER_ID
> sdk/CMakeLists: update variable

- sdk/CMakeLists.txt
- sdk/src/connections/target/buffer_processor.cpp
By passing the kernel space pointer to TOfiCompute decreases the processing time of the frame. If we copy it to user-space and after that process it, we can obtain a higher fps, and the DeInterleave function duration decreases from 145ms to 6ms, in case of QMP
> buffer_processor: copy data buffer to user space

- examples/tof-viewer/include/ADIToFRecorder.h
- examples/tof-viewer/src/ADIMainWindow.cpp
- examples/tof-viewer/src/ADIToFRecorder.cpp
Seems that when file size is large, several variables of type int will overflow. This happens when recording 'lr-native' (1024x1024) and more than 200 frames (205) to be precise.
Use size_t which should contain 8 bytes of unsinged integer. This should handle situations with larger files.
Files can't be infinite large since viewer has a upper limit of 300 frames to record.
> examples/viewer: Fix not being able to playback more than 200 frames

- CMakeLists.txt
- sdk/src/connections/target/adsd3500_sensor.cpp
The sdk can automatically detect the imager type based on ADSD3500 fw infrastructure.
> sdk: Remove cmake option 'USE_ADSD3030'

- azure-pipelines.yml
- ci/azure/nvidia-docker/Dockerfile
- ci/azure/readme.md
Adding Nvidia CI based on Jetson Linux 35.1.0 docker image, it contains:
* Kernel 5.10
* Ubuntu 20.04 Root File System
> Add Nvidia CI

- CMakeLists.txt
- sdk/src/connections/offline/offline_depth_sensor.cpp
- sdk/src/connections/offline/offline_depth_sensor.h
- sdk/src/connections/offline/offline_sensor_enumerator.cpp
The changes in this PR will allow users to evaluate depth compute on target (the embedded system to which the TOF camera is connected to) without hardware. A frame content will be available (as a binary file) to be passed through depth compute.
Things left to do:
- test this with a binary file
- upload the binary file to a server and make cmake download it
> On target make offline use depth compute

- examples/tof-viewer/src/ADIMainWindow.cpp
> Fixed viewer panels location

- sdk/src/cameras/itof-camera/camera_itof.cpp
- sdk/src/cameras/itof-camera/camera_itof.h
Example of how the config file should be filled:
```
"depthParams": {
"errata1": 1,
"dynamicModeSwitching": [
{
"mode": 2,
"repeat": 3
},
{
"mode": 3,
"repeat": 1
}
],
"0": {
```
> sdk: Support loading the DMS configuration from .json file

- examples/tof-viewer/include/ADIMainWindow.h
- examples/tof-viewer/src/ADIMainWindow.cpp
Stop button is working properly when streaming for the first time in ToF-viewer. After pressing the play button for a second time, the application remains focused on the "Open" menu. This will result in the need of two clicks to stop the stream (one to focus on the main panel and one for the stop button action).
To solve this, depth compute panel will be always focused when pressing the "play" button for streaming.
Same fix can be found in dev-5.1.0: https://github.com/analogdevicesinc/ToF/pull/669
> Solved stop button not working after first stream

- examples/tof-viewer/src/ADIMainWindow.cpp
When recording, the name of the file will be the following: "mode_modeNr_frames_time.bin"
> Changed name of saved frames when recording

- examples/tof-viewer/src/ADIMainWindow.cpp
Now for every when streaming, information window will be focused. This solves the PCM and Point Cloud cases, where there is no depth window and stop streaming button needs to be pressed two times to work.
> Changed window focus from depth to info window

- CMakeLists.txt
- cmake/version.h.cmakein
Since libaditof has been separated from examples, we have to keep different namings for versioning in order to avoid redefines and proper version control
> Cmake: change versioning name

- bindings/python/aditofpython.cpp
- bindings/python/examples/first_frame/first_frame.py
- bindings/python/examples/maskr_cnn/readme.md
This is a fix for the Python bindings issue in getting the confidence frame. In addition the first frame example has been expanded. Here is an example of the output now.
> Fix the Python bindings issue in getting the confidence frame

- CMakeLists.txt
This bug resulted in improper scaling that was obvious under dark conditions.
> update libaditof to set the metadata to 0 to eliminate its impact onscaling the AB image.

- examples/data_collect/main.cpp
* No arguments prints help.
* If -n is not specified then the system does not attempt to get frames.
* lcf, svf and ic must have arguments.
> Dc fw path fix

- sdcard-images-utils/nvidia/patches/hardware/nvidia/t23x/nv-public/0006-overlay-t23x-add-the-interrupt-gpio-pin.patch
- sdcard-images-utils/nvidia/patches/kernel/kernel-jammy-src/0006-arch-arm64-configs-defconfig-add-kernel-local-versio.patch
- sdcard-images-utils/nvidia/patches/nvidia-oot/drivers/0008-drivers-media-i2c-nv_adsd3500.c-request-gpio-as-inte.patch
- sdcard-images-utils/nvidia/patches/nvidia-oot/drivers/0009-drivers-media-i2c-nv_adsd3500.c-add-the-enable-fsync.patch
- sdcard-images-utils/nvidia/patches/nvidia-oot/drivers/0010-drivers-media-i2c-nv_adsd3500.c-pwm-device-is-added-.patch
- sdcard-images-utils/nvidia/patches/nvidia-oot/drivers/0011-drivers-media-i2c-nv_adsd3500.c-deleted-set-frame-ra.patch
- sdcard-images-utils/nvidia/scripts/system_upgrade/apply_patch.sh
1. add support to configure the external FSYNC with default fps
2. probing the interrupt GPIO
3. Custom v4l2-ctrl to switching between the external FSYNC and interrupt GPIO
4. The custom kernel version name adds the suffix "adi"
5. Handled the PWM device when the PWM is not mentioned in the device tree
6. Commented the build SDK function in the apply_patch.sh script
> Nvidia camera - add external fsync and interrupt gpio support

- sdcard-images-utils/nvidia/patches/hardware/nvidia/t23x/nv-public/0007-overlay-t23x-adsd3500-set-the-I2C-2-clock-frequency-.patch
- sdcard-images-utils/nvidia/patches/hardware/nvidia/t23x/nv-public/0008-overlay-t23x-adsd3500-dual-modified-the-camera-modul.patch
- sdcard-images-utils/nvidia/patches/nvidia-oot/drivers/0012-drivers-media-i2c-nv_adsd3500.c-set-one-pwm-time-per.patch
- sdcard-images-utils/nvidia/patches/nvidia-oot/drivers/0013-drivers-media-i2c-nv_adsd3500.c-set-the-default-gpio.patch
- sdcard-images-utils/nvidia/patches/ubuntu_overlay/usr/share/systemd/tof-power-en.sh
1. I2C clock frequency set to 1 MHz
2. Based on the module name, tof-power-en shell script executes the power sequence.
3. The gpio is configured as interrupt during the ADSD3500 driver probe.
> Nvidia camera - ADSD3500 driver optimization

- README.md
- bindings/python/examples/gesture_rec/readme.md
- bindings/python/examples/readme.md
- bindings/python/examples/showPointCloud/readme.md
- doc/itof/linux_build_instructions.md
- doc/itof/nxp_build_instructions.md
- doc/itof/windows_build_instructions.md
- scripts/windows/readme.md
- Updated build instructions to reference branch v6.1.0.
- Removed ToF ROS and Low-level examples.
- Removed references to two unused Python examples.
- gesture_rec and showpointcloud python examples now listed as deprecated.
> Readme updates

- apps/server/server.cpp
- Added timeout for **captureFramfromhardware**, **stop_stream_thread**.
- redesigned the logic of stopping server app when user press CTRL+C.
- made **adsd3500InterruptsQueue** thread safe by introducing mutex for it.
> Zmq redesign

- tests/sdk/sdk_stream_test/main.cpp
* Remove the possibility of '%' or '/' by 0
* CLang formatting
> Bud fix for sdk_stream_test
